In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('D:/Smartphone-Price-Prediction-Project/Smartphone-Price-Prediction-Project/data/raw/smartphones - smartphones.csv')

In [3]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [4]:
# Check initial data types and non-null counts
print(df.info())
print('Missing values: ', df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   str
 1   price      1020 non-null   str
 2   rating     879 non-null    float64
 3   sim        1020 non-null   str
 4   processor  1020 non-null   str
 5   ram        1020 non-null   str
 6   battery    1020 non-null   str
 7   display    1020 non-null   str
 8   camera     1019 non-null   str
 9   card       1013 non-null   str
 10  os         1003 non-null   str
dtypes: float64(1), str(10)
memory usage: 408.8 KB
None
Missing values:  model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [5]:
df['model'].sample(10)

933                     Tecno Camon 20 Premier
177                            Realme Narzo 50
989                            Sharp Aquos R5G
934        OPPO Reno 8 House of Dragon Edition
85                         Motorola Edge 30 5G
862                             Huawei Nova 7i
913               Apple iPhone 12 Mini (256GB)
792                                   OPPO A54
196    OPPO Reno 8 Pro House of Dragon Edition
523     Realme 9 Pro Plus 5G (8GB RAM + 256GB)
Name: model, dtype: str

In [6]:
def clean_model(x):
    """Clean the phone model name by removing tags like 4G, 5G, and Dual Sim."""
    
    x = x.split("(")[0]
    
    x = x.replace("5G", "").replace("4G", "").replace("Dual Sim", "")
    
    words = x.strip().split()
    if len(words) > 0 and len(words[-1]) == 4 and words[-1].isdigit():
        words.pop()
        
    return " ".join(words).strip()

df["Model"] = df["model"].apply(clean_model)

In [7]:
df['Model'].sample(10)

247         Apple iPhone 14
797             POCO M2 Pro
971           iQOO 7 Legend
461      Samsung Galaxy F22
244          Google Pixel 7
336         Infinix Note 12
282    Apple iPhone 14 Mini
985            Xiaomi Mi 10
789        Xiaomi Redmi 20X
184      Samsung Galaxy F24
Name: Model, dtype: str

In [8]:
# Dropping the model column 
df.drop('model', axis=1, inplace=True)

In [9]:
df['price'].sample(10)

678    ₹19,999
611       ₹699
330    ₹14,999
892    ₹15,999
950    ₹14,999
909    ₹38,700
895    ₹11,499
763    ₹15,499
356    ₹14,990
10     ₹18,999
Name: price, dtype: str

In [10]:
def clean_price(x):
  """Clean the price of phone by replacing '₹'."""
  x = x.strip().replace("₹", "").replace(",", "")
  return x

df['Price'] = df['price'].apply(clean_price)

In [11]:
# Dropping price column 
df.drop('price', axis=1, inplace=True)

In [12]:
# change the data type of Price column to float64
df['Price'] = df["Price"].astype('float64')

In [13]:
df['Price'].dtypes

dtype('float64')

In [23]:
df['sim'].sample(10)

633     Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster
57           Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster
506               Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC
624                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi
76              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
407             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
1000                                           Dual Sim
658                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi
390                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi
256             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC
Name: sim, dtype: str

In [46]:
def clean_sim_ds(x):
  """Cleans the sim of phone into Dual and Single"""
  if "Dual" in x:
    return 1
  elif "Single" in x:
    return 0
  else:
    return np.nan
  
df["Sim"] = df["sim"].apply(clean_sim_ds)

In [44]:
# 5G column - yes or no
def clean_sim_5G(x):
  """Clean the sim column into 5G - Yes or No"""
  if "5G" in x:
    return 1
  else:
    return 0

df['5G'] = df['sim'].apply(clean_sim_5G)

In [49]:
df['5G'].dtypes

dtype('int64')

In [36]:
def clean_sim_irb(x):
  """Cleans the sim into IR column - Yes and No"""
  if "IR" in x:
    return 1
  else:
    return 0
  
df['IrBlaster'] = df["sim"].apply(clean_sim_irb)

In [42]:
def clean_sim_nfc(x):
  """Cleans the sim column into NFC column - Yes and No"""
  if "NFC" in x:
    return 1
  else:
    return 0
df["NFC"] = df["sim"].apply(clean_sim_nfc)

In [52]:
# drop sim column 
df.drop('sim', axis=1, inplace=True)

In [54]:
def clean_processor_speed(x):
  """Extract the numeric processor speed (GHz) from the processor string."""
  if "GHz" in x:
    return x.strip().split(",")[-1].strip().split(" ")[0].replace("GHz", "")
  else:
    return np.nan
  
df['Speed'] = df['processor'].apply(clean_processor_speed)

In [59]:
# change the datatype of Speed column to float
df["Speed"] = df["Speed"].astype("float64")

In [62]:
def clean_processor_core(x):
  """Extract the core count (e.g., Octa, Quad) from the processor string."""

  if "Core" in x:
      x = x.strip().split(",")
      c = " ".join(x).strip().split(" ")
      if "Core" in c:
        index = c.index("Core")
        return c[index - 1]
      else:
        return np.nan
  else:
      return np.nan

df["Core"] = df["processor"].apply(clean_processor_core)

In [64]:
df['Core'].unique()

<ArrowStringArray>
['Octa', 'Hexa', 'Quad', nan, 'Dual', 'Single']
Length: 6, dtype: str

In [65]:
# map the Core column as per the unique values
core_map = {
    'Octa': 8,
    'Hexa': 6,
    'Quad': 4,
    'Dual': 2,
    'Single': 1
}

df['Core'] = df['Core'].map(core_map)

In [69]:
def clean_processor_pn(x):
    """Extract processor brand/series from processor column."""
    
    if pd.isna(x):
        return np.nan

    c = str(x).split(",")[0].strip().lower()

    if "snapdragon" in c or "sanpdragon" in c or "qualcomm" in c:
        return "snapdragon"
    elif "dimensity" in c:
        return "dimensity"
    elif "helio" in c:
        return "helio"
    elif "unisoc" in c or "spreadtrum" in c or "sc9863a" in c or "sc6531e" in c or "tiger" in c:
        return "unisoc"
    elif "exynos" in c or "samsung" in c:
        return "exynos"
    elif "bionic" in c or "a13" in c or "a14" in c or "a15" in c or "a16" in c or "fusion" in c:
        return "bionic"
    elif "google" in c or "tensor" in c:
        return "google"
    elif "kirin" in c:
        return "kirin"
    else:
        return np.nan

df["ProcessorName"] = df["processor"].apply(clean_processor_pn)

In [74]:
df[['processor', 'ProcessorName']].sample(10)

                                         processor ProcessorName
355   Unisoc SC9863A, Octa Core, 1.6 GHz Processor        unisoc
446   Dimensity 1080, Octa Core, 2.6 GHz Processor     dimensity
157   Snapdragon 695, Octa Core, 2.2 GHz Processor    snapdragon
538        Helio G99, Octa Core, 2.2 GHz Processor         helio
291        Exynos  850, Octa Core, 2 GHz Processor        exynos
866     Snapdragon 439, Octa Core, 2 GHz Processor    snapdragon
663         Tiger T616, Octa Core, 2 GHz Processor        unisoc
995      Exynos 7885, Octa Core, 2.2 GHz Processor        exynos
584   Snapdragon 695, Octa Core, 2.2 GHz Processor    snapdragon
556     Exynos  990, Octa Core, 2.73 GHz Processor        exynos

In [75]:
# drop the processor column 
df.drop('processor', axis=1, inplace=True)

In [77]:
def clean_ram_ram(x):
    """Normalize RAM to a numeric GB value directly using float."""
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    
    if "GB RAM" in x:
        ram = x.split(",")[0].replace("GB RAM", "").replace("GB", "").strip()
        return float(ram)
            
    elif "MB RAM" in x:
        ram = x.split(",")[0].replace("MB RAM", "").replace("MB", "").strip()
        return round(float(ram) / 1024, 4)

    else:
        return np.nan

df['Ram'] = df['ram'].apply(clean_ram_ram)

In [86]:
df[['ram','Ram']].sample(10)

                          ram  Ram
632   4 GB RAM, 64 GB inbuilt  4.0
777  8 GB RAM, 256 GB inbuilt  8.0
208  8 GB RAM, 128 GB inbuilt  8.0
104  8 GB RAM, 128 GB inbuilt  8.0
698  8 GB RAM, 256 GB inbuilt  8.0
87   8 GB RAM, 128 GB inbuilt  8.0
850  6 GB RAM, 128 GB inbuilt  6.0
345  6 GB RAM, 128 GB inbuilt  6.0
828  6 GB RAM, 128 GB inbuilt  6.0
169   4 GB RAM, 64 GB inbuilt  4.0